### PR TITLE
Unbreak master

### PR DESCRIPTION
**Pull request by ttung**
Fix how we use `starfish.display`.
remove `assay_comparison.py`

### CODE REVIEW

**Comment by kne42** [comment]
tbh not sure if I wanna resurrect `starfish.plot`. I'll leave @ambrosejcarr to decide on this one

**Comment by ambrosejcarr** [comment]
@ttung @kne42 It looks like part of this PR is likely adequate to unbreak master -- just the notebook changes are needed to cover the refactor that was made for `starfish.display`, not any of the subsequent resurrection.

**Comment by ttung** [comment]
The `assay_comparison` notebook refers to `starfish.plot`.

**Comment by kne42** [comment]
I deleted the `.py` and forgot to delete its notebook counterpart and that's why it's still there.

**Comment by ttung** [comment]
Ahh, should I drop the assay_comparison notebook then?

**Comment by kne42** [comment]
Yeah, I would say drop that and remove `starfish.plot` and then it should be good to go

**Comment by ttung** [comment]
Ok, updated.

**Comment by ttung** [comment]
Notebooks aren't run as part of non-master travis runs. :)

**Comment by kne42** [comment]
Ah, that would explain why it passed in my PR.

**Pull request merged**
