### PR TITLE
Sync STARmap notebook

### PR DESCRIPTION
**Pull request by ttung**
I forgot to do this in #1150

### CODE REVIEW

**Comment by ttung** [comment]
I'm just going to land this. :)

**Comment by ambrosejcarr** [comment]
Couldn't even wait 2 minutes... ;-)

**Comment by ttung** [comment]
I have no patience... which results in me breaking builds all the time. :)

**Comment by ambrosejcarr** [comment]
Must be rough. I have no idea what that's like, of course.  👀

**Pull request merged**
