### PR TITLE
Regenerated jupyter notebooks from .py files

### PR DESCRIPTION
**Pull request by ttung**
#596 changed it such that travis only runs `make fast` instead of `make all`, which meant we were not validating that the jupyter notebooks stayed in sync.  #583 changed the .py file without updating the .ipynb file.

Test plan: `make validate_notebooks` passes.

### CODE REVIEW

**Comment by joshmoore** [comment]
Hmmm... apologies for losing that, but I'm confused. Doesn't `all` just depend on `fast` which in turn depends on `lint mypy test`?

**Comment by ttung** [comment]
ummm, yes, you are right.

however, `validate_notebooks` is hooked onto all, and not `fast`.  I guess we could switch it to `fast` since it is pretty fast.

**Comment by joshmoore** [comment]
Ah, ok. I see via the `all:` in subdirs.mk. Up to you if you want fast to have validate_notebooks or call all from `Syntax and Tests` _or_ Add another job which is just for notebook validation. I don't have a feeling for relative times.

**Comment by ttung** [comment]
Note #634.  That solves the issue. :)

**Comment by joshmoore** [comment]
New I should have put a `#deprecated` on all. :) Ok. Landing that and dealing with the conflict. Open to just killing `fast` then.

**Pull request merged**
