### PR TITLE
add codebooks to mask autofluorescence

### PR DESCRIPTION
**Pull request by ambrosejcarr**
Adds functions to produce two codebooks: 

1. A codebook that will decode any spot that is present in _all rounds and channels_
2. A codebook that will decode any spot that is present in _all rounds of each specific channel_ (separately)

These codebooks identify autofluorescent spots, and can be used with #1030 to either mask these spots or visualize them with contrasting colors.

### CODE REVIEW

**Comment by kevinyamauchi** [comment]
Good idea! I haven't had a chance to look at the code yet, but one high level question: many autofluorescent things have fairly broad fluorescence and thus will be visible in multiple channels. Do you think there's a reasonable way to generalize without remaking `from_code_array()`?

**Comment by ambrosejcarr** [comment]
> Good idea! I haven't had a chance to look at the code yet, but one high level question: many autofluorescent things have fairly broad fluorescence and thus will be visible in multiple channels. Do you think there's a reasonable way to generalize without remaking `from_code_array()`?

This made me realize there are simpler ways to create these. I pushed a new commit. when you look at the code now, is it clear how you'd create something yourself? 

You could also skip `Codebook._create_codebook` completely, since `Codebook` is a subclass of `xarray`, you could make a codebook directly from a `numpy` array. e.g. `constitutive_fluorescence_mask` could just as easily be constructed doing: 

```python
import numpy as np
from starfish import Codebook

N_CH = 5
N_ROUND = 3

code_names = ["autofluorescence"]
Codebook(
    data=np.ones((1, N_CH, N_ROUND)),
    coords=(
        ("target", ["autofluorescence"]),
        ("c", range(N_CH)),
        ("r", range(N_ROUND))
    )
)
```

**Comment by ttung** [comment]
Can this be implemented as a filter?  Logically, that makes more sense to me.

**Comment by ambrosejcarr** [comment]
Interesting. It'd be a filter on the `IntensityTable`, right? I could do that, and agree that would make sense.

**Comment by ttung** [comment]
> Interesting. It'd be a filter on the IntensityTable, right? I could do that, and agree that would make sense.

I don't know that it has to be one vs the other.  You could definitely do it in image space.

If you _must_ do it in codebook space, I would suggest that you make a method that takes an existing codebook, and adds these code points.  The resulting codebook can be used to decode an image and you get out what you expect (throwing away the wonky points).

**Comment by ambrosejcarr** [comment]
@ttung I adjusted these to be additive to existing codebooks.

**Comment by ttung** [comment]
What happens if someone does this to a codebook that has a code at that position?  IMO, we should fail in that case.

**Comment by ambrosejcarr** [comment]
I haven't seen much interest in using the content of this PR so I suggest closing it for the time being unless someone objects.

**Pull request closed without merging**
