### PR TITLE
Migrate docker to conda

### PR DESCRIPTION
**Pull request by joshmoore**
Since the other .travis.yml builds test the REQUIREMENTS*
files, this now tests an environment.yml in docker. There's
an outstanding issue with slicedimage and its enum34 dep
which will need to be fixed before this is mergeable.

see https://github.com/spacetx/starfish/issues/44

### CODE REVIEW

**Comment by joshmoore** [comment]
Re-opening to test again fixed master

**Comment by joshmoore** [comment]
Green, but I'd still hold off until slicedimage==0.0.2.

**Comment by joshmoore** [comment]
Not sure what's going on with travis. Closing & re-opening to see if it triggers.

**Comment by ambrosejcarr** [comment]
Travis seems mad at you @joshmoore .

**Comment by joshmoore** [comment]
I know! Don't know _what_ I've done to hir.

**Comment by joshmoore** [comment]
(Turns out a typo in the .travis.yml was preventing travis from running)

**Pull request closed without merging**
