### PR TITLE
Starfish pre-alpha -> beta

### PR DESCRIPTION
**Pull request by ttung**
Traditionally alpha = in house use, beta = external testers.

Test plan: lol

### CODE REVIEW

**Comment by neuromusic** [comment]
Are we still in beta? If so, when are we out of beta?

**Comment by ambrosejcarr** [comment]
Depending on what our target feature set is, there could be arguments for all kinds of phasing for starfish.

I'd vaguely argue that we have key features that we still want to add, and some questions around acquisition and architecture that block us from being "stable".

We feel like we're in "limited beta" to me, simply because each user tends to need some attention to be able to adapt starfish to their use cases.

I'd say we're out of beta when we have a product we're confident our target users can use to accomplish the product's supported use cases with limited developer support.

**Comment by ttung** [comment]
I prefer just plain old beta.

1. I don't want to discourage someone from picking it up because they think limited = google wave, where you have to be invited and all that.
2. It's not entirely clear what limited is.  It can mean different things to different people.

We are definitely not out of beta.

**Comment by ambrosejcarr** [comment]
> I prefer just plain old beta.

Yes I think this is the right way to communicate our state to new users. 👍

**Pull request merged**
