### PR TITLE
Alternate approach of hiding stuff

### PR DESCRIPTION
**Pull request by ttung**
Doing it in a web editor.  What could go wrong?

### CODE REVIEW

**Comment by ttung** [comment]
Derp, this doesn't work. :(

**Comment by ttung** [comment]
Ok, I'm back: this sort of works.  If you run `dir(starfish)`, you still see these symbols.  However, if you're in ipython and you type `starfish.` and hit tab, you do _not_ see these symbols.  Not sure what is qualified as working.

**Comment by ambrosejcarr** [comment]
Can you screenshot the outputs and dump em here?

**Comment by ttung** [comment]
```
In [1]: import starfish                                                                                                                                        
/Users/ttung/microscopy/starfish/.venv/lib/python3.6/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}

In [2]: dir(starfish)                                                                                                                                          
Out[2]: 
['Codebook',
 'Experiment',
 'FieldOfView',
 'ImageStack',
 'IntensityTable',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__is_release_tag__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_display',
 '_get_versions',
 '_version',
 '_warnings',
 'codebook',
 'compat',
 'config',
 'display',
 'errors',
 'experiment',
 'expression_matrix',
 'image',
 'imagestack',
 'intensity_table',
 'multiprocessing',
 'pipeline',
 'segmentation_mask',
 'spacetx_format',
 'spots',
 'starfish',
 'types',
 'util']

In [3]: starfish. 
 Codebook           display()          expression_matrix  imagestack         pipeline           starfish           starfish.wdl      
 codebook           errors             FieldOfView        intensity_table    segmentation_mask  types                                
 compat             Experiment         image              IntensityTable     spacetx_format     util                                 
 config             experiment         ImageStack         multiprocessing    spots              starfish.egg-info/                                             
                                                                                                                                                               
```

**Comment by ambrosejcarr** [comment]
Oh, I want to hide stuff like `codebook` and `compat`. Don't think this is working.

**Comment by ttung** [comment]
This hides `pkg_resources`, `warnings`, and `get_versions` without the explicit `del` statements.

**Comment by ambrosejcarr** [comment]
Oh, got it. 👍 I'm fine with this if you prefer it to my delete approach. I misinterpreted and thought you were addressing the larger issue.

**Comment by ttung** [comment]
no, i am unaware of a great way to address the larger issue. :(

**Pull request closed without merging**
