### PR TITLE
Move Indices and Coordinates to starfish.constants

### PR DESCRIPTION
**Pull request by ttung**
Test: python -v -m starfish 2>&1 | egrep '^import' yields no fat libraries.

### CODE REVIEW

**Comment by ambrosejcarr** [comment]
Is the problem here that importing Indices requires an import of Image? If that's the case, could we move Indices (constants) up to the main level instead of having to import it in weird places?

**Comment by ttung** [comment]
Yes, I agree it would be better if Indices got moved.  However, it so very logically belongs with Image.  Can you think of a better hierarchy that splits ImageStack from Image? :)

**Comment by ambrosejcarr** [comment]
I have no problem with constants being a top-level file. I see it as the place where all the constants for the repo go. We could just add a comment that describes where Indices is used.

**Comment by ttung** [comment]
screen shot 2018-05-18 at 10 12 40 am
well this is disappointing.

**Pull request merged**
