### PR TITLE
Update Starfish CI and dependencies

### PR DESCRIPTION
**Pull request by njmei**
This ended up being quite a doozy...

Summary of changes:
- Switch to GitHub-actions from now unaccessible Travis CI
- Update starfish dependencies (and fix **numerous** tests and warnings)
    Key dependencies that have been bumped up and will be tested by CI include:
    - xarray==0.19.0
    - scikit-image==0.18.3
    - scipy==1.7.1
    - scikit-learn==0.24.2
    - pandas==1.3.2
    - numpy==1.21.2
- Drop python 3.6 support
- Add python 3.9 support

For blow by blow please see individual commit messages. I've tried to organize and add as much useful relevant documentation as possible.

### CODE REVIEW

**Comment by njmei** [comment]
@mattcai @neuromusic @berl Not sure who has the keys to this repository anymore, but this PR should address quite a few current issues for this project. The biggest being that the existing Travis CI appears to no longer work (and required custom build agents I *think*).

My fork of this project appears to be passing almost all tests with the exception of two notebooks which run fine on my local machine but appear to be encountering a permissions issue (maybe from trying to download cloudfront data? Maybe something else?) for DARTFISH and SeqFISH notebooks.

**Comment by berl** [comment]
@njmei  I am super stoked about this.

... and before I can finish my comment, @ttung swoops in and merges it. 

 thanks @ttung!  now we know you're watching....

**Comment by ttung** [comment]
Ok, I fixed the notebooks! Hope you're doing well! :)

**Comment by neuromusic** [comment]
epic work @njmei!! thanks for the help @ttung :D

**Pull request merged**
