### PR TITLE
conda: use strict requirements in docker

### PR DESCRIPTION
**Pull request by ttung**

### CODE REVIEW

**Comment by joshmoore** [comment]
Re-launched `make slow` due to the following validation error that (a) I'm not seeing locally and (b) I can't explain:

```
============================================================
<xarray.Dataset>
Dimensions:                        (c: 4, features: 51, r: 4)
Coordinates:
    z                              (features) int32 ...
    y                              (features) int32 ...
    x                              (features) int32 ...
    radius                         (features) int32 ...
    z_min                          (features) int32 ...
    z_max                          (features) int32 ...
    y_min                          (features) int32 ...
    y_max                          (features) int32 ...
    x_min                          (features) int32 ...
    x_max                          (features) int32 ...
    intensity                      (features) float64 ...
    spot_id                        (features) int32 ...
  * features                       (features) int32 0 1 2 3 4 ... 46 47 48 49 50
    xc                             (features) float32 ...
    yc                             (features) float32 ...
    zc                             (features) float32 ...
  * c                              (c) int32 0 1 2 3
  * r                              (r) int32 0 1 2 3
Data variables:
    __xarray_dataarray_variable__  (features, c, r) float64 ...
============================================================
Opened /tmp/tmpj2s5621e/results/spots.nc in 0.01008749008178711s.
Likely just spots
Invalid xarray: 0
Temporary files kept under:
```

**Comment by ttung** [comment]
> Re-launched `make slow` due to the following validation error that (a) I'm not seeing locally and (b) I can't explain:

this is fixed by #1004 (this surfaced because i refreshed the dependencies, picking up click 7.0)

**Comment by ttung** [comment]
Incidentally, this is the sort of fun that happens when we don't have pinned dependencies. :)

**Comment by joshmoore** [comment]
Gotcha. I'll review the differences between click 6 & 7 and see if we can expect any other gotchas.

**Comment by joshmoore** [comment]
Closing and re-opening to pull in gh-1004

**Pull request merged**
