### PR TITLE
adding mouse v human example to starfish.data

### PR DESCRIPTION
**Pull request by shanaxel42**
#1725

### CODE REVIEW

**Comment by neuromusic** [comment]
Do we have any tests for the datasets module? Verifying the hash of a FOV or something?

**Comment by shanaxel42** [comment]
> Do we have any tests for the datasets module? Verifying the hash of a FOV or something?

No - but those tests would take a long time.

**Comment by ttung** [comment]
> Do we have any tests for the datasets module? Verifying the hash of a FOV or something?

spacetx file format is somewhat resilient against data corruption.  I think the goal of tests for `starfish.data` should be to verify that the data is *available*.  If we can verify that the top level `experiment.json` is accessible, that is good enough for me.  More than that requires more effort than I think is worth doing.

**Comment by neuromusic** [comment]
okay, that all makes sense.

Let's get this in and add some data availability tests as part of the durability epic.

**Pull request merged**
