### PR TITLE
Unify FunctionSource in Map and Reduce

### PR DESCRIPTION
**Pull request by ttung**
This is needed to enable #1539, as that imports `FunctionSource` from `ImageStack` (and `Map`/`Reduce` import `ImageStack`).

Note that this is not entirely for free.  The function aliases (example: where we alias 'max' to 'amax' for `FunctionSource.np`) now come from one source, which may or may not be desirable.

Test plan: travis yo

### CODE REVIEW

**Comment by ttung** [comment]
> general question, and sorry if this has already been discussed. But what's the advantage of having the function source logic over just have a function parameter passed into reduce? Like func=np.max

as discussed offline, allowing arbitrary callables to be passed in makes provenance tracking extremely challenging.  However, we could plausibly use code inspection to solve that problem.

**Comment by ambrosejcarr** [comment]
> as discussed offline, allowing arbitrary callables to be passed in makes provenance tracking extremely challenging. However, we could plausibly use code inspection to solve that problem.

If you see a path where this is achievable, I believe usability benefits strongly from just passing in the function.

**Comment by ttung** [comment]
> If you see a path where this is achievable, I believe usability benefits strongly from just passing in the function.

It's _somewhat_ achievable.  I'll look into it.

**Comment by ambrosejcarr** [comment]
> It's somewhat achievable. I'll look into it.

After PR is merged is OK with me, if this blocks.

**Comment by ttung** [comment]
> After PR is merged is OK with me, if this blocks.

#1568

**Pull request merged**
