### PR TITLE
RFC/WIP: document use of segmentation & target assignment

### PR DESCRIPTION
**Pull request by kne42**
please let me know how to make this example shorter/actually correct (expression matrix returned is null)

### CODE REVIEW

**Comment by ambrosejcarr** [comment]
I would suggest a few changes: 

Outside the example: run the script to the point of decoding and save the resulting intensity table as a netcdf object. Put that object on s3 somewhere. 

The script can then:
1. Load the intensity table
2. Load any auxiliary images needed for segmentation
3. Run segmentation
4. Assign spots
5. Create an expression matrix

If the expression matrix is empty, it could be because any of the earlier steps are wrong. I'd look at intermediate steps. I'll be available today on slack if you want to ping me with questions.

**Comment by ambrosejcarr** [comment]
@kne42 checking in on this PR. What's the plan here?

**Comment by kne42** [comment]
Since whatever pipeline was on here is not working properly, I thought I'd apply some of the same techniques you were talking about but with a different dataset:
1. run ISS.ipynb
2. save out registered images to s3

Then the tutorial structure would look like:
1. load up ISS data and registered images from s3
2. _Spot Finding_: use `BlobDetector` on registered images to get intensity table
3. _Spot Decoding_: use `experiment.codebook.decode_per_round_max`
4. _Segmenting Cells_: use `WatershedSegmenter` on registered images and nuclei
5. _Assigning Spots to Cells_: use `Label` on masks and decoded table

we can also forget about 2 & 3 and precompute them on s3 if you feel it isn't useful information, but the gist of this example will be to regurgitate ISS.ipynb

**Comment by ambrosejcarr** [comment]
Sounds good!

**Pull request closed without merging**
