### PR TITLE
Script to generate a multi-FOV 3D synthetic input set

### PR DESCRIPTION
**Pull request by ttung**
To run, this requires:
https://github.com/spacetx/slicedimage/pull/7
https://github.com/spacetx/slicedimage/pull/8
https://github.com/spacetx/slicedimage/pull/9
https://github.com/spacetx/slicedimage/pull/10

### CODE REVIEW

**Comment by ambrosejcarr** [comment]
Thanks for this!

I'm finding it hard to run, I'll wait until the `slicedimage` PRs get merged, and you can then pin the correct slicedimage version so I can run the example here (#10) gave me an error, so I'm not sure if there is any one branch that works -- if there is please feel free to correct me and I'll review sooner.

**Comment by ttung** [comment]
This is now ready for review, and should run without any magic.

**Comment by dganguli** [comment]
Coordinates is missing z for both nuclei and hybridization images. Re-name ch -> c and hyb -> h. in the file format. Else, looks good to me!

**Comment by ttung** [comment]
> Coordinates is missing z for both nuclei and hybridization images.

Added missing 'z'.

> Re-name ch -> c and hyb -> h. in the file format.

https://github.com/spacetx/starfish/pull/181

**Pull request merged**
