### PR TITLE
Pre-calculate xmin,xmax,ymin,ymax attrs on IntensityTable before overlap processing 

### PR DESCRIPTION
**Pull request by shanaxel42**
This specifically addresses #1363. The slowdown was due to repeatedly recalculating the min/max physical coordinates on the IntensityTables when trying to find overlaps. By calculating and storing the bounding box coordinates first, `IntensityTable.concatenate_intensity_tables(overlap_strategy=TAKE_MAX)` on the three tables provided by @njmei  was reduced from 479.860 seconds to 148.285 seconds. This should also scale much better (linearly) now since we only do the expensive min/max calculations once per intensity table at the beginning.

### CODE REVIEW

**Comment by ttung** [comment]
Design question: is there anything stopping someone from mutating the IntensityTable after the bounding boxes are calculated?  If not, the bounding boxes could plausibly become outdated.  Would it make sense to compute the bounding boxes once per concat operation?

Separately, what's the critical path now?

**Comment by shanaxel42** [comment]
> Design question: is there anything stopping someone from mutating the IntensityTable after the bounding boxes are calculated? If not, the bounding boxes could plausibly become outdated. Would it make sense to compute the bounding boxes once per concat operation?
> 
> Separately, what's the critical path now?

I mean the bounding boxes are calculated as part of the `IntensityTable.concatenate_intensity_tables()` call so I'm not sure how someone would mess with the intensity tables in the middle of that method unless they ripped out the code.

**Comment by ttung** [comment]
> I mean the bounding boxes are calculated as part of the IntensityTable.concatenate_intensity_tables() call so I'm not sure how someone would mess with the intensity tables in the middle of that method unless they ripped out the code.

Yeah, I suspect that code path is fine, but the attrs are still on the IntensityTable objects.

**Comment by shanaxel42** [comment]
> > I mean the bounding boxes are calculated as part of the IntensityTable.concatenate_intensity_tables() call so I'm not sure how someone would mess with the intensity tables in the middle of that method unless they ripped out the code.
> 
> Yeah, I suspect that code path is fine, but the attrs are still on the IntensityTable objects.

I can clear them after...or I guess store them separately from the intensity tables. The min/max calls take an incredibly long amount of time on the data nick sent though so calculating them more then once per table is significant.

**Comment by ttung** [comment]
> I can clear them after...or I guess store them separately from the intensity tables. The min/max calls take an incredibly long amount of time on the data nick sent though so calculating them more then once per table is significant.

Why does it take so long to calculate a max of 1700 numbers?  Are we doing something wrong?

**Comment by shanaxel42** [comment]
> > I can clear them after...or I guess store them separately from the intensity tables. The min/max calls take an incredibly long amount of time on the data nick sent though so calculating them more then once per table is significant.
> 
> Why does it take so long to calculate a max of 1700 numbers? Are we doing something wrong?

I'M SUPER DUMB and did not do enough profiling, this was a great point. Should have been using np.max/np.min instead of the built in min/max functions. Closing this PR, another one coming

**Pull request closed without merging**
