### PR TITLE
[1/5] stack to experiment

### PR DESCRIPTION
**Pull request by ambrosejcarr**
These 5 PRs refactor some code to make the API match the proposal in #292. The easiest way to review these PRs is probably to load up PR [5/5], reinstall starfish, import it, and explore the API. 

In this PR: 
- Rename stack to experiment, propagate changes across files and notebooks.

### CODE REVIEW

**Comment by ambrosejcarr** [comment]
> should be in this diff:
>
> {stack,experiment}.org should be renamed.

I'm confused by what change you want here. The purpose of this PR is to rename those. 

Is the request changes a request to add a follow-up PR with these changes? 

> should be done, but not in this diff:
>
> - extract a hyb, set of aux images, and codebook at the top of each notebook, rather than continuing to reference the experiment throughout the code.
> - tests like the dataset fixtures and starfish/test/pipeline/test_filter.py should not reference experiment, as they're being done on an ImageStack.

**Comment by ttung** [comment]
> I'm confused by what change you want here. The purpose of this PR is to rename those.

The .org field should be renamed.  It is not meaningful.

> Is the request changes a request to add a follow-up PR with these changes?

PR is ++, but issue is also acceptable. :)

**Comment by ambrosejcarr** [comment]
> The .org field should be renamed. It is not meaningful.

Got it. Sorry for confusion.

**Comment by ambrosejcarr** [comment]
> tests like the dataset fixtures and starfish/test/pipeline/test_filter.py should not reference experiment, as they're being done on an ImageStack.

Issue #401

**Pull request merged**
