### PR TITLE
update requirements

### PR DESCRIPTION
**Pull request by ttung**

### CODE REVIEW

**Comment by ttung** [comment]
> Is this just a periodic "we updated and these still work"?

yup, precisely.

**Comment by joshmoore** [comment]
Testing this locally I also get:

```
-matplotlib==2.2.3
+matplotlib==3.0.0
```

do you want to add a `<3` pin in this PR?

**Comment by ttung** [comment]
> Testing this locally I also get:
>>
>>-matplotlib==2.2.3
>>+matplotlib==3.0.0
>> 
> do you want to add a <3 pin in this PR?

Hm... which REQUIREMENTS file are you using?  pip does not have a constraint resolver, so the version constraints are obtained from the first instance that it sees.  I see that in the new makefile, REQUIREMENTS-NOTEBOOK is installed first.  Maybe that's it?

I would suggest this for the Makefile rules:

```
install-src:
	pip install -e .
	pip install --force-reinstall --upgrade -r REQUIREMENTS-DEV.txt -r REQUIREMENTS-NOTEBOOK.txt
	pip freeze

install-pypi:
	pip install starfish
	pip install -r REQUIREMENTS-NOTEBOOK.txt
```

**Comment by joshmoore** [comment]
No change with the commit from https://github.com/spacetx/starfish/pull/586#issuecomment-423081456:


```
diff --git a/REQUIREMENTS.txt b/REQUIREMENTS.txt
index f362cde..da86ccf 100644
--- a/REQUIREMENTS.txt
+++ b/REQUIREMENTS.txt
@@ -6,22 +6,22 @@ chardet==3.0.4
 click==6.7
 cloudpickle==0.5.6
 cycler==0.10.0
-dask==0.19.1
+dask==0.19.2
 decorator==4.3.0
 diskcache==3.0.6
 idna==2.7
 jsonschema==2.6.0
 kiwisolver==1.0.1
-matplotlib==2.2.3
+matplotlib==3.0.0
 more-itertools==4.3.0
-networkx==2.1
+networkx==2.2
 numpy==1.15.1
 packaging==17.1
 pandas==0.23.4
 Pillow==5.2.0
 pluggy==0.7.1
 py==1.6.0
-pyparsing==2.2.0
+pyparsing==2.2.1
 pytest==3.8.0
 python-dateutil==2.7.3
 pytz==2018.5
```

Tested with:

```
FROM python:3.6
RUN useradd -m starfish
USER starfish
COPY --chown=starfish:starfish . /src
WORKDIR /src
RUN python -m venv venv
RUN bash -c "source venv/bin/activate && make install-src"
RUN bash -c "source venv/bin/activate && make refresh_all_requirements"
RUN git diff
```

Pinning matplotlib produces:

```
diff --git a/REQUIREMENTS.txt b/REQUIREMENTS.txt
index f362cde..885ceee 100644
--- a/REQUIREMENTS.txt
+++ b/REQUIREMENTS.txt
@@ -6,7 +6,7 @@ chardet==3.0.4
 click==6.7
 cloudpickle==0.5.6
 cycler==0.10.0
-dask==0.19.1
+dask==0.19.2
 decorator==4.3.0
 diskcache==3.0.6
 idna==2.7
@@ -14,14 +14,14 @@ jsonschema==2.6.0
 kiwisolver==1.0.1
 matplotlib==2.2.3
 more-itertools==4.3.0
-networkx==2.1
+networkx==2.2
 numpy==1.15.1
 packaging==17.1
 pandas==0.23.4
 Pillow==5.2.0
 pluggy==0.7.1
 py==1.6.0
-pyparsing==2.2.0
+pyparsing==2.2.1
 pytest==3.8.0
 python-dateutil==2.7.3
 pytz==2018.5
diff --git a/REQUIREMENTS.txt.in b/REQUIREMENTS.txt.in
index bdb3bcd..865ebf3 100644
--- a/REQUIREMENTS.txt.in
+++ b/REQUIREMENTS.txt.in
@@ -1,6 +1,6 @@
 click
 jsonschema
-matplotlib
+matplotlib < 3
 numpy != 1.13.0
 pandas >= 0.23.4
 pytest>=3.6.3
```

**Comment by ttung** [comment]
Oh I see, you're refreshing all requirements.  I thought you were just installing from the new requirements.txt from this PR.

I'll let @ambrosejcarr and @dganguli weigh in on the need for a pin for matplotlib < 3.

**Comment by ambrosejcarr** [comment]
Matplotlib 3.0 is new! 

Matplotlib often "breaks everything" with major version changes, with 2.0 it took them until 2.0.4 to play nicely with the ecosystem. 

I'm OK pinning this, but we should revisit in a month or two.

**Comment by ttung** [comment]
Well, this won't be a problem until the next time we run `make refresh_all_requirements`.

**Pull request merged**
