### PR TITLE
[easy] fix documentation about how to install for developers.

### PR DESCRIPTION
**Pull request by ttung**
install-dev covers installation of strict dependencies, `pip install -e`, and the installation of CI tools.

### CODE REVIEW

**Comment by ambrosejcarr** [comment]
I think we probably need some kind of instructions about how to install make on osx if we go this route. (xcode tools).

**Comment by ttung** [comment]
Do we not expect developers to be able to install make...?

**Comment by ambrosejcarr** [comment]
> Do we not expect developers to be able to install make...?

Sorry, I was looking at the changes out of context. You make a good point, but maybe better safe than sorry? Could just be a link out to other instructions.

**Comment by ttung** [comment]
Well, WSL users are going to be totally lost then. :)

**Comment by ttung** [comment]
Updated with a link to https://developer.apple.com/library/archive/technotes/tn2339/_index.html

**Pull request merged**
