### PR TITLE
Make in-place opt-in.

### LINKED ISSUE #384: Make out-of-place computation the default
- Make in-place=False the default for apply loops and filters in `ImageStack`.

### PR DESCRIPTION
**Pull request by ttung**
Default is out-of-place.

Depends on #598 

Fixes #384

### CODE REVIEW

**Comment by ttung** [comment]
> Next step here is that I think this breaks the ISS and allen_smFISH notebooks (since they still assume in_place=True)

Um, are you sure?  I ran make -j run_notebooks and that passed.

**Comment by ambrosejcarr** [comment]
> Um, are you sure? I ran make -j run_notebooks and that passed.

No, but I go look at the notebooks and they're not assigning the outputs of the filters to anything. So, unless the filters don't matter, I don't think the notebooks should be passing? The ISS notebook, for example, has this block of code: 

```python
from starfish.image import Filter

# filter raw data
masking_radius = 15
filt = Filter.WhiteTophat(masking_radius, is_volume=False)
for img in images:
    filt.run(img, verbose=True)
```

**Comment by ttung** [comment]
> No, but I go look at the notebooks and they're not assigning the outputs of the filters to anything. So, unless the filters don't matter, I don't think the notebooks should be passing? The ISS notebook, for example, has this block of code:

LOL that is amazing.  So either the in-place code is hilariously broken or we don't need filters.

**Comment by ttung** [comment]
Wait, we have zero asserts in the notebooks now... of course they pass. 😠

**Comment by ttung** [comment]
Ok fixed.  It turns out _not_ filtering didn't trigger the small handful of asserts that are in the notebook. hahahaha.

**Comment by ambrosejcarr** [comment]
My understanding of the current testing plan is: 

1. Update .py files
3. Test the .py files (which have really stringent tests!) 
3. Use passing .py files to update notebooks

Is this right @shanaxel42 ?

**Comment by shanaxel42** [comment]
Yea @ambrosejcarr that flow is correct. Once the api test refactor is merged they will catch stuff like this. The tests didn't tigger an error here because they don't currently test on any of the values from the notebooks.

**Pull request merged**
